name: Service CI

on:
  pull_request:
      branches:
        - main

jobs:
  service-ci:
    uses: FA9-lab/platform-workflows/.github/workflows/node-service-ci.yml@main
    with:
      node-version: '22'
